name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1

      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

  tests:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar testes
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build do projeto
        run: npm run build

  deploy-dockerhub:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/imagem-sistema-email-compjr:${{ github.sha }} .

      - name: Push da imagem Docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/imagem-sistema-email-compjr:${{ github.sha }}

      - name: Atualizar tag latest
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/imagem-sistema-email-compjr:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/imagem-sistema-email-compjr:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/imagem-sistema-email-compjr:latest
          
  deploy-render:
    runs-on: ubuntu-latest
    needs: deploy-dockerhub
    steps:
      - name: Trigger Deploy no Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
